### ISSUE TITLE
Is it possible to retrieve configuration name from publish profile name?

### ISSUE THREAD

**Issue by xperiandri** [nil4/dotnet-transform-xdt#11]
Instead of configuration name

**Comment by nil4** [comment]
@xperiandri that is an interesting question, and I think you would probably have a better chance of finding an answer on StackOverflow or a Microsoft ASP.NET repositories (e.g. [aspnet/Tooling](https://github.com/aspnet/Tooling)). I personally don't know if or how it can be done.

I'll close the issue since the question doesn't appear related to code in this repo.
