### ISSUE TITLE
Outdated Microsoft.DotNet.Xdt.Tools project level tool in nuget

### ISSUE THREAD

**Issue by lcsanchez** [nil4/dotnet-transform-xdt#41]
Thanks for all the work on this project!

I was attempting to use the project level `Microsoft.DotNet.Xdt.Tools` tool in my project and noticed it still seems to have the issue whitespace preservation issues described in https://github.com/nil4/dotnet-transform-xdt/issues/4.

The two other [nuget packages](https://www.nuget.org/profiles/nil4) appear to have been published more recently. Is the recommendation to use the global tool over the project level tool?

**Comment by nil4** [comment]
@lcsanchez which version of `Microsoft.DotNet.Xdt.Tools` is referenced in your project? I believe 1.x versions had these whitespace issues, while 2.0 and later should include the fix. Check your project file, it should have a reference similar to this:

```xml
<DotNetCliToolReference Include="Microsoft.DotNet.Xdt.Tools" Version="2.0.0" />
```

If you use an earlier version, try referencing 2.0.0 instead &mdash; that should fix the issue.

**Comment by lcsanchez** [comment]
You are absolutely correct. I must have been using an old version previously and gotten confused. Everything appears to be working perfectly. Thank you so much for the quick reply!

**Comment by lcsanchez** [comment]
Ok, sorry for the confusion. The project I'm working in has some pretty large app config files. As far as I can tell, it looks like maybe this issue is limited to entire sections being replaced.

Here is an example of what I'm seeing.

If there is a `App.config` file with the following contents:
```xml
<configuration>
  <appSettings>
    <add key="one" value="one-value" />
    <add key="two" value="two-value" />
    <add key="three" value="three-value" />
  </appSettings>
</configuration>
```

Then my transform has:

```xml
<configuration xmlns:xdt="http://schemas.microsoft.com/XML-Document-Transform">
  <appSettings xdt:Transform="Replace">
    <add key="one-new" value="one-new-value" />
    <add key="two-new" value="two-new-value" />
    <add key="three-new" value="three-new-value" />
  </appSettings>
</configuration>
```

The resulting xml turns out like this:

```xml
<configuration>
  <appSettings><add key="one-new" value="one-new-value" /><add key="two-new" value="two-new-value" /><add key="three-new" value="three-new-value" /></appSettings>
</configuration>
```

From what I can tell, any xml that isn't changed by the transform doesn't change in formatting.

I did just try this with the global tool `v2.1.1` and had the same results. Since it's only formatting, I think this will be something I can work around.

**Comment by nil4** [comment]
I can confirm what you're seeing. 

Just to note that this code is based on the former XDT project, published by Microsoft on Codeplex (now archived at https://archive.codeplex.com/?p=xdt), which I ported to .NET Core. 

Any existing bugs or unimplemented features were also ported wholesale.  For example, the existing test cases [here](https://github.com/nil4/dotnet-transform-xdt/tree/master/dotnet-xdt.tests/Resources) do not define the expected behavior for multi-line `xdt:Transform="Replace"` content. So the issue that you identified might have been there since the original code was written.

I am therefore leaning towards keeping the current behavior, as compatibility with the previous XDT codebase is important. That said, if you are willing to investigate this, and propose a PR with the fix and test cases to prevent future regressions, I would be happy to review and incorporate it.
